apps/dashboard/urls.py
from django.urls import path
from . import views


app_name = 'dashboard'



urlpatterns = [
    path('teacher/', views.teacher_dashboard, name='teacher_dashboard'),
    path('my-subjects/', views.my_subjects, name='my_subjects'),
    path('student/', views.student_dashboard, name='student_dashboard'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('apps.accounts.urls')),
    path('dashboard/', include('apps.dashboard.urls')),
    path("admin-panel/", include("apps.admin_panel.urls")),
    path('logout/', LogoutView.as_view(), name='logout'),

]

# MEDIA (faqat development uchun)
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

templates/base/dashboard_base.html
{% load static %}
<!DOCTYPE html>
<html lang="uz">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Dashboard{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">
    <link rel="stylesheet" href="{% static 'css/teacher_dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'css/teacher_my_subjects.css' %}">

    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>
<body>

<div class="dashboard-wrapper">

    <aside class="sidebar">
        {% include "base/sidebar.html" %}
    </aside>

    <main class="content">
        {% block content %}
        {% endblock %}
    </main>

</div>


</body>
</html>

templates/base/sidebar.html
            <div class="logo-section">
                <div class="logo">
                    <i class="fas fa-graduation-cap"></i>
                </div>
                <h1 class="school-name">AJOU <span>school</span></h1>
            </div>

            <nav class="nav-menu">
                <ul>
                    <li>
                        <a href="{% url 'dashboard:teacher_dashboard' %}">
                            <i class="fas fa-tachometer-alt"></i>
                            <span>Dashboard</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'dashboard:my_subjects' %}">
                            <i class="fas fa-users"></i>
                            <span>Mening fanlarim</span>
                        </a>
                    </li>
                    <li class="active">
                        <a href="time-table.html">
                            <i class="fas fa-calendar-alt"></i>
                            <span>Dars jadval</span>
                        </a>
                    </li>
                    <li>
                        <a href="assignments.html">
                            <i class="fas fa-tasks"></i>
                            <span>Topshiriqlar</span>
                        </a>
                    </li>
                    <li>
                        <a href="tests.html">
                            <i class="fas fa-file-alt"></i>
                            <span>Testlar</span>
                        </a>
                    </li>
                    <li>
                        <a href="attendance.html">
                            <i class="fas fa-clipboard-check"></i>
                            <span>Davomat</span>
                        </a>
                    </li>
                    <li>
                        <a href="profile.html">
                            <i class="fas fa-user-circle"></i>
                            <span>Profilim</span>
                        </a>
                    </li>
                    <li>
                        <a href="setting.html">
                            <i class="fas fa-cog"></i>
                            <span>Sozlamalar</span>
                        </a>
                    </li>
                </ul>
            </nav>

    <div class="sidebar-user">
        {{ request.user.username }} · O‘qituvchi
    </div>